# Copyright (c) 2025, NVIDIA CORPORATION.  All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: 2

project_name: cns

builds:
  - id: cnsctl
    binary: cnsctl
    mod_timestamp: &build-timestamp '{{ .CommitTimestamp }}'
    dir: cmd/cnsctl
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    flags:
      - -trimpath
    ldflags: &build-ldflags |
      -w
      -s
      -extldflags "-static"
      -X github.com/NVIDIA/cloud-native-stack/pkg/cli.version={{.Version}}
      -X github.com/NVIDIA/cloud-native-stack/pkg/cli.commit={{.ShortCommit}}
      -X github.com/NVIDIA/cloud-native-stack/pkg/cli.date={{.Date}}
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

  - id: cnsd
    binary: cnsd
    mod_timestamp: &build-timestamp '{{ .CommitTimestamp }}'
    dir: cmd/cnsd
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    flags:
      - -trimpath
    ldflags: &build-ldflags |
      -w
      -s
      -extldflags "-static"
      -X github.com/NVIDIA/cloud-native-stack/pkg/api.version={{.Version}}
      -X github.com/NVIDIA/cloud-native-stack/pkg/api.commit={{.ShortCommit}}
      -X github.com/NVIDIA/cloud-native-stack/pkg/api.date={{.Date}}
    goos:
      - linux
    goarch:
      - amd64
      - arm64

universal_binaries:
  - name_template: "cnsctl"
    replace: false  # keep platform-specific binaries too

gomod:
  proxy: false

sboms:
  - artifacts: binary

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
  algorithm: sha256

snapshot:
  version_template: "{{ .Tag }}-next"

report_sizes: true

metadata:
  mod_timestamp: "{{ .CommitTimestamp }}"

release:
  github:
    owner: mchmarny  # NVIDIA
    name: cloud-native-stack
  prerelease: auto

kos:
  - id: cnsctl
    build: cnsctl
    repositories:
      - ghcr.io/mchmarny/cns
    base_image: nvcr.io/nvidia/cuda:13.1.0-runtime-ubuntu24.04
    platforms:
      - linux/amd64
      - linux/arm64
    tags:
      - latest
      - "{{.Tag}}"
    preserve_import_paths: false
    bare: true

  - id: cnsd
    build: cnsd
    repositories:
      - ghcr.io/mchmarny/cnsd
    base_image: gcr.io/distroless/static:nonroot
    platforms:
      - linux/amd64
      - linux/arm64
    tags:
      - latest
      - "{{.Tag}}"
    preserve_import_paths: false
    bare: true

archives:
  - id: cnsctl
    ids:
      - cnsctl
    formats:
      - binary
    name_template: "{{ .Binary }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}"

  - id: cnsctl-homebrew
    ids:
      - cnsctl
    formats:
      - tar.gz
    name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE*
      - README*

brews:
  - name: cnsctl
    ids:
      - cnsctl-homebrew
    repository:
      owner: mchmarny
      name: homebrew-cloud-native-stack
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/mchmarny/cloud-native-stack"
    description: "CLI for generating validated GPU-accelerated Kubernetes configurations"
    license: "Apache-2.0"
    install: |
      bin.install "cnsctl"
    test: |
      system "#{bin}/cnsctl", "version"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^lint:"
      - "^chore: readme"
      - "^chore: bump version"
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: "Tasks"
      regexp: '^.*?chore(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: "Bug fixes"
      regexp: '^.*?bug(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Others
      order: 999
