# Centralized Tool Versions
#
# Single source of truth for tool versions used in CI/CD and local development.
# GitHub Actions and Makefiles should reference this file.

# Language Versions
languages:
  go: '1.25'

# Build Tools
build_tools:
  goreleaser: 'v2'
  ko: 'v0.18.0'

# Linting
linting:
  golangci_lint: 'v2.6'

# E2E Testing Tools
testing_tools:
  kind: '0.27.0'
  ctlptl: '0.8.43'
  tilt: '0.35.0'
  helm: 'v3.17.0'
