# Copyright (c) 2025, NVIDIA CORPORATION.  All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Language Versions
languages:
  go: '1.25'

# Build Tools
build_tools:
  goreleaser: 'v2'
  ko: 'v0.18.0'
  crane: 'v0.20.6'

# Linting
linting:
  golangci_lint: 'v2.6'
  addlicense: 'v1.1.1'

# E2E Testing Tools
testing_tools:
  kind: '0.27.0'
  ctlptl: '0.8.43'
  tilt: '0.35.0'
  helm: 'v3.17.0'
