# Copyright (c) 2025, NVIDIA CORPORATION.  All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: 'Security Scan with Trivy'
description: 'Run Trivy vulnerability scan and upload SARIF results to GitHub Security'

inputs:
  scan_type:
    description: 'Scan type (fs, image, config, etc.)'
    required: false
    default: 'fs'
  scan_ref:
    description: 'Scan reference (path or image)'
    required: false
    default: '.'
  severity:
    description: 'Severity levels to report (UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL)'
    required: false
    default: 'HIGH,CRITICAL'
  output_file:
    description: 'Output SARIF file name'
    required: false
    default: 'trivy-results.sarif'
  category:
    description: 'GitHub Security category for upload'
    required: false
    default: 'trivy'
  skip_dirs:
    description: 'Comma-separated list of directories to skip'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Run Trivy Security Scan
      uses: aquasecurity/trivy-action@b6643a29fecd7f34b3597bc6acb0a98b03d33ff8  # v0.33.1
      with:
        scan-type: ${{ inputs.scan_type }}
        scan-ref: ${{ inputs.scan_ref }}
        ignore-unfixed: true
        hide-progress: true
        format: 'sarif'
        output: ${{ inputs.output_file }}
        severity: ${{ inputs.severity }}
        exit-code: '0'
        skip-dirs: ${{ inputs.skip_dirs }}
      continue-on-error: true

    - name: Check SARIF file exists
      id: check_sarif
      shell: bash
      run: |
        set -euo pipefail
        if [[ -f "${{ inputs.output_file }}" ]]; then
          echo "exists=true" >> "$GITHUB_OUTPUT"
        else
          echo "exists=false" >> "$GITHUB_OUTPUT"
        fi

    - name: Upload SARIF to GitHub Security
      if: steps.check_sarif.outputs.exists == 'true'
      uses: github/codeql-action/upload-sarif@b20883b0cd1f46c72ae0ba6d1090936928f9fa30  # v4.32.0
      with:
        sarif_file: ${{ inputs.output_file }}
        category: ${{ inputs.category }}
