# Copyright (c) 2025, NVIDIA CORPORATION.  All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "needs-triage"]

body:
  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      options:
        - label: I searched existing issues and found no duplicates
          required: true
        - label: I can reproduce this issue consistently
          required: true
        - label: This is not a security vulnerability (use [Security Advisories](https://github.com/NVIDIA/cloud-native-stack/security/advisories/new) instead)
          required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: What happened and what did you expect?
    validations:
      required: true

  - type: dropdown
    id: impact
    attributes:
      label: Impact
      description: How severe is this issue for you?
      options:
        - Blocking (cannot proceed)
        - High (major functionality broken)
        - Medium (workaround exists)
        - Low (minor issue)
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      options:
        - CLI (cnsctl)
        - API server (cnsd)
        - Recipe engine / data
        - Bundlers (gpu-operator, network-operator, etc.)
        - Collectors / snapshotter
        - Validator
        - Docs / examples
        - Other / Unknown
    validations:
      required: true

  - type: dropdown
    id: regression
    attributes:
      label: Regression?
      description: Did this work in a previous version?
      options:
        - "Yes, this worked before (please specify version below)"
        - "No, this is a new use case"
        - "Unknown / first time using this feature"
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      placeholder: |
        1. Step one
        2. Step two
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      placeholder: |
        - CNS version (CLI `cnsctl version`, API image tag, or commit SHA):
        - Install method (release binary / build from source / container image):
        - Platform (eks/gke/aks/self-managed):
        - Kubernetes version:
        - OS (ubuntu/cos/other) + version:
        - Kernel version:
        - GPU type (h100/gb200/a100/l40/other):
        - Workload intent (training/inference):
      value: |
        - CNS version (CLI `cnsctl version`, API image tag, or commit SHA):
        - Install method (release binary / build from source / container image):
        - Platform (eks/gke/aks/self-managed):
        - Kubernetes version:
        - OS (ubuntu/cos/other) + version:
        - Kernel version:
        - GPU type (h100/gb200/a100/l40/other):
        - Workload intent (training/inference):
    validations:
      required: true

  - type: textarea
    id: command
    attributes:
      label: Command / Request Used
      description: Paste the exact CLI command(s) or API request(s) that triggered the issue.
      placeholder: |
        ```bash
        cnsctl recipe --snapshot ... --intent training
        ```

        ```bash
        curl "http://localhost:8080/v1/recipe?..."
        ```
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Logs / Error Output
      description: Include relevant logs or error messages. Redact any credentials or secrets.
      render: shell

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Anything else that might help (regression? recent upgrade? related issues?).
    validations:
      required: false