apiVersion: v1
kind: ServiceAccount
metadata:
  name: eidos
  namespace: gpu-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: eidos
  namespace: gpu-operator
rules:
  - apiGroups: [""]
    resources: ["*"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: eidos
  namespace: gpu-operator
subjects:
  - kind: ServiceAccount
    name: eidos
    namespace: eidos
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: eidos
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: eidos-node-reader
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]
  - apiGroups: ["*"]
    resources: ["clusterpolicies"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: eidos-node-reader
subjects:
  - kind: ServiceAccount
    name: eidos
    namespace: gpu-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: eidos-node-reader