package bundler

import (
	"github.com/NVIDIA/cloud-native-stack/pkg/bundler/common"
	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promauto"
)

var (
	// bundlesGeneratedTotal counts total bundles generated by type and status.
	bundlesGeneratedTotal = promauto.NewCounterVec(
		prometheus.CounterOpts{
			Name: "eidos_bundles_generated_total",
			Help: "Total number of bundles generated by type and status",
		},
		[]string{"bundler_type", "status"},
	)

	// bundleDurationSeconds measures time to generate bundles.
	bundleDurationSeconds = promauto.NewHistogramVec(
		prometheus.HistogramOpts{
			Name:    "eidos_bundle_duration_seconds",
			Help:    "Time taken to generate bundle by type",
			Buckets: prometheus.DefBuckets,
		},
		[]string{"bundler_type"},
	)

	// bundleSizeBytes tracks size of generated bundles.
	bundleSizeBytes = promauto.NewGaugeVec(
		prometheus.GaugeOpts{
			Name: "eidos_bundle_size_bytes",
			Help: "Size of generated bundle in bytes by type",
		},
		[]string{"bundler_type"},
	)

	// bundleFilesTotal counts files generated per common.
	bundleFilesTotal = promauto.NewGaugeVec(
		prometheus.GaugeOpts{
			Name: "eidos_bundle_files_total",
			Help: "Number of files generated in bundle by type",
		},
		[]string{"bundler_type"},
	)

	// bundleErrorsTotal counts errors during bundle generation.
	bundleErrorsTotal = promauto.NewCounterVec(
		prometheus.CounterOpts{
			Name: "eidos_bundle_errors_total",
			Help: "Total number of errors during bundle generation by type",
		},
		[]string{"bundler_type", "error_type"},
	)

	// bundleValidationFailuresTotal counts validation failures.
	bundleValidationFailuresTotal = promauto.NewCounterVec(
		prometheus.CounterOpts{
			Name: "eidos_bundle_validation_failures_total",
			Help: "Total number of bundle validation failures by type",
		},
		[]string{"bundler_type"},
	)
)

// recordBundleGenerated records a bundle generation event.
func recordBundleGenerated(bundlerType common.BundleType, success bool) {
	status := "success"
	if !success {
		status = "failure"
	}
	bundlesGeneratedTotal.WithLabelValues(string(bundlerType), status).Inc()
}

// recordBundleDuration records the duration of bundle generation.
func recordBundleDuration(bundlerType common.BundleType, seconds float64) {
	bundleDurationSeconds.WithLabelValues(string(bundlerType)).Observe(seconds)
}

// recordBundleSize records the size of the generated common.
func recordBundleSize(bundlerType common.BundleType, bytes int64) {
	bundleSizeBytes.WithLabelValues(string(bundlerType)).Set(float64(bytes))
}

// recordBundleFiles records the number of files in the common.
func recordBundleFiles(bundlerType common.BundleType, count int) {
	bundleFilesTotal.WithLabelValues(string(bundlerType)).Set(float64(count))
}

// recordBundleError records an error during bundle generation.
func recordBundleError(bundlerType common.BundleType, errorType string) {
	bundleErrorsTotal.WithLabelValues(string(bundlerType), errorType).Inc()
}

// recordValidationFailure records a validation failure.
func recordValidationFailure(bundlerType common.BundleType) {
	bundleValidationFailuresTotal.WithLabelValues(string(bundlerType)).Inc()
}
