name: 'GHCR Login'
description: 'Authenticate to GitHub Container Registry'

inputs:
  registry:
    description: 'Container registry URL'
    required: false
    default: 'ghcr.io'
  username:
    description: 'Registry username (defaults to github.actor)'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Login to Container Registry
      uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username != '' && inputs.username || github.actor }}
        password: ${{ github.token }}
