kind: recipeResult
apiVersion: cns.nvidia.com/v1alpha1
metadata:
  timestamp: "2026-01-12T21:53:03Z"
  version: v0.12.3-next
  appliedOverlays:
    - base
    - eks
    - eks-training
criteria:
  service: eks
  accelerator: h100
  intent: training
  os: any
constraints:
  - name: K8s.server.version
    value: '>= 1.30'
  - name: OS.sysctl./proc/sys/kernel/osrelease
    value: '>= 6.8'
  - name: OS.release.ID
    value: ubuntu
  - name: OS.release.VERSION_ID
    value: "24.04"
componentRefs:
  - name: cert-manager
    type: Helm
    source: https://charts.jetstack.io
    version: v1.17.2
    valuesFile: components/cert-manager/values.yaml
  - name: gpu-operator
    type: Helm
    source: ""
    version: v25.3.4
    valuesFile: components/gpu-operator/eks-training.yaml
    overrides:
      gdrcopy:
        enabled: false
  - name: nvsentinel
    type: Helm
    source: oci://ghcr.io/nvidia/nvsentinel
    version: v0.6.0
    dependencyRefs:
      - cert-manager
  - name: skyhook-operator
    type: Helm
    source: oci://ghcr.io/nvidia/skyhook
    version: v0.4.0
    valuesFile: components/skyhook-operator/values.yaml
deploymentOrder:
  - cert-manager
  - gpu-operator
  - nvsentinel
  - skyhook-operator
